FROM jenkins/jenkins
USER root
RUN export VERSION_PATH="/var/jenkins_home/.version"
COPY ./version_tag.sh /var/jenkins_home/version_tag.sh
RUN chmod +x /var/jenkins_home/version_tag.sh
RUN apt-get update -qq \
 && apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
RUN apt-get update  -qq \
 && apt-get -y install docker-ce
RUN curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN usermod -aG docker jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.27.12"
RUN jenkins-plugin-cli --plugins "docker-plugin:1.6.1"
RUN jenkins-plugin-cli --plugins "docker-workflow:580.vc0c340686b_54"
